---
name: nokogiri
version: '1.11'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: 7a105f52053ce1c708b605dfa9c1ab8473424036
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
